import {
  Warehouse,
  StockItem,
  StockMovement,
  PurchaseOrder,
  GRN,
  StockTransfer,
  StockAdjustment,
  Supplier,
  BarcodeItem,
  BatchItem,
  SerialNumberItem,
  ExpiryAlert,
  CycleCount,
  InventoryValuation,
  InventoryStats,
} from '../types/inventoryTypes';

const unavailable = async (): Promise<never> => {
  throw new Error('Inventory service is not configured. Connect the inventory API to load data.');
};

export const inventoryApi = {
  getStats: async (): Promise<InventoryStats> => ({
    totalStock: 0,
    availableStock: 0,
    reservedStock: 0,
    lowStockCount: 0,
    outOfStockCount: 0,
    damagedStock: 0,
    incomingStock: 0,
    outgoingStock: 0,
    warehouseCount: 0,
    supplierCount: 0,
    inventoryValue: 0,
    todaysStockMovements: 0,
  }),
  getWarehouses: async (): Promise<Warehouse[]> => [],
  getWarehouseById: async (): Promise<Warehouse | undefined> => undefined,
  createWarehouse: unavailable as (data: Omit<Warehouse, 'id' | 'totalSKUs' | 'currentCapacityPercent' | 'createdAt'>) => Promise<Warehouse>,
  updateWarehouse: unavailable as (id: string, data: Partial<Warehouse>) => Promise<Warehouse>,
  deleteWarehouse: unavailable as (id: string) => Promise<boolean>,
  getStockItems: async (): Promise<StockItem[]> => [],
  getStockItemById: async (): Promise<StockItem | undefined> => undefined,
  getStockMovements: async (): Promise<StockMovement[]> => [],
  createStockMovement: unavailable as (data: Omit<StockMovement, 'id' | 'timestamp'>) => Promise<StockMovement>,
  getPurchaseOrders: async (): Promise<PurchaseOrder[]> => [],
  createPurchaseOrder: unavailable as (data: Omit<PurchaseOrder, 'id' | 'poNumber' | 'createdAt'>) => Promise<PurchaseOrder>,
  updatePOStatus: unavailable as (id: string, status: PurchaseOrder['status']) => Promise<PurchaseOrder>,
  getGRNs: async (): Promise<GRN[]> => [],
  createGRN: unavailable as (data: Omit<GRN, 'id' | 'grnNumber'>) => Promise<GRN>,
  getTransfers: async (): Promise<StockTransfer[]> => [],
  createTransfer: unavailable as (data: Omit<StockTransfer, 'id' | 'transferNumber' | 'createdAt'>) => Promise<StockTransfer>,
  updateTransferStatus: unavailable as (id: string, status: StockTransfer['status']) => Promise<StockTransfer>,
  getAdjustments: async (): Promise<StockAdjustment[]> => [],
  createAdjustment: unavailable as (data: Omit<StockAdjustment, 'id' | 'adjustmentNumber' | 'createdAt'>) => Promise<StockAdjustment>,
  getSuppliers: async (): Promise<Supplier[]> => [],
  createSupplier: unavailable as (data: Omit<Supplier, 'id' | 'totalOrdersCount' | 'totalSpent'>) => Promise<Supplier>,
  getBarcodes: async (): Promise<BarcodeItem[]> => [],
  generateBarcode: unavailable as (sku: string, type: 'code128' | 'qr' | 'ean13') => Promise<BarcodeItem>,
  getBatches: async (): Promise<BatchItem[]> => [],
  getSerialNumbers: async (): Promise<SerialNumberItem[]> => [],
  getExpiryAlerts: async (): Promise<ExpiryAlert[]> => [],
  getCycleCounts: async (): Promise<CycleCount[]> => [],
  createCycleCount: unavailable as (data: Omit<CycleCount, 'id' | 'countNumber' | 'createdAt'>) => Promise<CycleCount>,
  getValuation: async (): Promise<InventoryValuation> => ({
    valuationMethod: 'Weighted Average',
    totalStockValue: 0,
    totalUnits: 0,
    inventoryCost: 0,
    estimatedProfit: 0,
    categoryBreakdown: [],
  }),
};