import { UserPermission } from '@/types/auth';

export interface MenuItem {
  id: string;
  title: string;
  href?: string;
  icon: string; // Dynamic icon string resolved to Lucide component
  permission?: UserPermission;
  children?: MenuItem[];
}

export const SIDEBAR_MENU: MenuItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    href: '/dashboard',
    icon: 'LayoutDashboard',
    permission: 'view:dashboard',
  },
  {
    id: 'catalog',
    title: 'Catalog',
    icon: 'ShoppingBag',
    permission: 'view:catalog',
    children: [
      {
        id: 'products',
        title: 'Products List',
        href: '/dashboard/catalog/products',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'product-new',
        title: 'Add Product (Wizard)',
        href: '/dashboard/catalog/products/new',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'categories',
        title: 'Categories',
        href: '/dashboard/catalog/categories',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'brands',
        title: 'Brands',
        href: '/dashboard/catalog/brands',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'collections',
        title: 'Collections',
        href: '/dashboard/catalog/collections',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'product-types',
        title: 'Product Types',
        href: '/dashboard/catalog/product-types',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'attributes',
        title: 'Attributes & Groups',
        href: '/dashboard/catalog/attributes',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'attribute-values',
        title: 'Attribute Values',
        href: '/dashboard/catalog/attribute-values',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
      {
        id: 'tags',
        title: 'Tags Directory',
        href: '/dashboard/catalog/tags',
        icon: 'CircleDot',
        permission: 'view:catalog',
      },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory Hub',
    icon: 'Warehouse',
    permission: 'view:inventory',
    children: [
      {
        id: 'inventory-overview',
        title: 'Control Center',
        href: '/dashboard/inventory/dashboard',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'stock',
        title: 'Stock Control',
        href: '/dashboard/inventory/stock',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'warehouses',
        title: 'Warehouses',
        href: '/dashboard/inventory/warehouses',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'stock-adjustments',
        title: 'Stock Adjustments',
        href: '/dashboard/inventory/stock-adjustments',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'stock-transfers',
        title: 'Stock Transfers',
        href: '/dashboard/inventory/stock-transfers',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'purchase-orders',
        title: 'Purchase Orders',
        href: '/dashboard/inventory/purchase-orders',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'grn',
        title: 'Goods Received (GRN)',
        href: '/dashboard/inventory/grn',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'suppliers',
        title: 'Suppliers Directory',
        href: '/dashboard/inventory/suppliers',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'barcodes',
        title: 'Barcode Generator',
        href: '/dashboard/inventory/barcodes',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'batches',
        title: 'Batch & Lot Control',
        href: '/dashboard/inventory/batches',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'serial-numbers',
        title: 'Serial Numbers',
        href: '/dashboard/inventory/serial-numbers',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'expiry-management',
        title: 'Expiry & FEFO',
        href: '/dashboard/inventory/expiry-management',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'cycle-count',
        title: 'Cycle Counts',
        href: '/dashboard/inventory/cycle-count',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'inventory-valuation',
        title: 'FIFO/LIFO Valuation',
        href: '/dashboard/inventory/inventory-valuation',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
      {
        id: 'inventory-reports',
        title: 'Inventory Reports',
        href: '/dashboard/inventory/inventory-reports',
        icon: 'CircleDot',
        permission: 'view:inventory',
      },
    ],
  },
  {
    id: 'customers',
    title: 'Customers CRM',
    icon: 'Users',
    permission: 'view:customers',
    children: [
      {
        id: 'customers-list',
        title: 'Directory Ledger',
        href: '/dashboard/customers/list',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'customer-groups',
        title: 'Pricing Groups',
        href: '/dashboard/customers/groups',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'customer-segments',
        title: 'Dynamic Segments',
        href: '/dashboard/customers/segments',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'customer-wallet',
        title: 'Wallets Register',
        href: '/dashboard/customers/wallet',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'reward-points',
        title: 'Loyalty points',
        href: '/dashboard/customers/reward-points',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'support-tickets',
        title: 'Support SLA Queue',
        href: '/dashboard/customers/support-tickets',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'reviews',
        title: 'Review Auditing',
        href: '/dashboard/customers/reviews',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'customer-notes',
        title: 'CRM Directives',
        href: '/dashboard/customers/notes',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'customer-activity',
        title: 'Audit Stream',
        href: '/dashboard/customers/activity',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
      {
        id: 'customer-reports',
        title: 'Metrics & Reports',
        href: '/dashboard/customers/reports',
        icon: 'CircleDot',
        permission: 'view:customers',
      },
    ],
  },
  {
    id: 'orders',
    title: 'Orders',
    icon: 'ShoppingCart',
    permission: 'view:orders',
    children: [
      {
        id: 'orders-list',
        title: 'Orders Ledger',
        href: '/dashboard/orders/list',
        icon: 'CircleDot',
        permission: 'view:orders',
      },
      {
        id: 'picking-packing',
        title: 'Picking & Packing Queue',
        href: '/dashboard/orders/picking-packing',
        icon: 'CircleDot',
        permission: 'view:orders',
      },
      {
        id: 'shipments',
        title: 'Shipments & Dispatch',
        href: '/dashboard/orders/shipments',
        icon: 'CircleDot',
        permission: 'view:orders',
      },
      {
        id: 'invoices',
        title: 'Invoicing Desk',
        href: '/dashboard/orders/invoices',
        icon: 'CircleDot',
        permission: 'view:orders',
      },
      {
        id: 'returns',
        title: 'Returns & Refunds',
        href: '/dashboard/orders/returns',
        icon: 'CircleDot',
        permission: 'view:orders',
      },
    ],
  },
 {
    id: 'payments',
    title: 'Payments',
    icon: 'CreditCard',
    permission: 'view:payments',
    children: [
      {
        id: 'payment-dashboard',
        title: 'Dashboard',
        href: '/payments/dashboard',
        icon: 'CircleDot',
        permission: 'view:payments',
      },
      {
        id: 'transactions',
        title: 'Transactions',
        href: '/payments/transactions',
        icon: 'CircleDot',
        permission: 'view:payments',
      },
      {
        id: 'invoices',
        title: 'Invoices',
        href: '/payments/invoices',
        icon: 'CircleDot',
        permission: 'manage:payments',
      },
      {
        id: 'credit-notes',
        title: 'Credit Notes',
        href: '/payments/credit-notes',
        icon: 'CircleDot',
        permission: 'manage:payments',
      },
      {
        id: 'debit-notes',
        title: 'Debit Notes',
        href: '/payments/debit-notes',
        icon: 'CircleDot',
        permission: 'manage:payments',
      },
      {
        id: 'refunds',
        title: 'Refunds',
        href: '/payments/refunds',
        icon: 'CircleDot',
        permission: 'manage:payments',
      },
      {
        id: 'wallet',
        title: 'Wallet',
        href: '/payments/wallet',
        icon: 'CircleDot',
        permission: 'view:payments',
      },
      {
        id: 'gateways',
        title: 'Gateways',
        href: '/payments/gateways',
        icon: 'CircleDot',
        permission: 'view:payments',
      },
      {
        id: 'audit-logs',
        title: 'Audit Logs',
        href: '/payments/audit-logs',
        icon: 'CircleDot',
        permission: 'view:payments',
      },
    ],
  },
  {
    id: 'finance',
    title: 'Finance',
    icon: 'Banknote',
    permission: 'view:reports',
    children: [
      {
        id: 'reconciliation',
        title: 'Reconciliation',
        href: '/payments/reconciliation',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'settlements',
        title: 'Settlements',
        href: '/payments/settlements',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'tax-reports',
        title: 'Tax Reports',
        href: '/payments/tax-reports',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'finance-reports',
        title: 'Finance Reports',
        href: '/payments/finance-reports',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
    ],
  },
  {
    id: 'marketing',
    title: 'Marketing',
    icon: 'Megaphone',
    permission: 'view:marketing',
    children: [
      {
        id: 'marketing-dashboard',
        title: 'Dashboard',
        href: '/dashboard/marketing',
        icon: 'LayoutDashboard',
        permission: 'view:marketing',
      },
      {
        id: 'campaigns',
        title: 'Campaigns',
        href: '/campaigns',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'coupons',
        title: 'Coupons',
        href: '/coupons',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'discount-rules',
        title: 'Discount Rules',
        href: '/discount-rules',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'flash-sales',
        title: 'Flash Sales',
        href: '/flash-sales',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'banners',
        title: 'Banners',
        href: '/banners',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'promotional-pages',
        title: 'Promotional Pages',
        href: '/promotional-pages',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'gift-cards',
        title: 'Gift Cards',
        href: '/gift-cards',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'referral-program',
        title: 'Referral Program',
        href: '/referral-program',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'loyalty-program',
        title: 'Loyalty Program',
        href: '/loyalty-program',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'abandoned-cart',
        title: 'Abandoned Carts',
        href: '/abandoned-cart',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'product-recommendations',
        title: 'Product Recommendations',
        href: '/product-recommendations',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'email-campaigns',
        title: 'Email Campaigns',
        href: '/email-campaigns',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'sms-campaigns',
        title: 'SMS Campaigns',
        href: '/sms-campaigns',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'whatsapp-campaigns',
        title: 'WhatsApp Campaigns',
        href: '/whatsapp-campaigns',
        icon: 'CircleDot',
        permission: 'view:marketing',
      },
      {
        id: 'push-notifications',
        title: 'Push Notifications',
        href: '/push-notifications',
        icon: 'CircleDot',
        permission: 'manage:marketing',
      },
      {
        id: 'marketing-analytics',
        title: 'Analytics',
        href: '/marketing-analytics',
        icon: 'CircleDot',
        permission: 'view:marketing',
      }
    ],
  },
  
 
  {
    id: 'cms',
    title: 'CMS & Content',
    icon: 'FileText',
    permission: 'view:cms',
    children: [
      {
        id: 'cms-dashboard',
        title: 'CMS Overview',
        href: '/cms/dashboard',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-pages',
        title: 'Pages Directory',
        href: '/cms/pages',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-blogs',
        title: 'Blog Articles',
        href: '/cms/blogs',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-categories',
        title: 'Blog Categories',
        href: '/cms/blogs/categories',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-tags',
        title: 'Content Tags',
        href: '/cms/blogs/tags',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-media',
        title: 'Media Library (DAM)',
        href: '/cms/media',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-menus',
        title: 'Menu Builder',
        href: '/cms/menus',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-faqs',
        title: 'Knowledge Base & FAQs',
        href: '/cms/faqs',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-testimonials',
        title: 'Customer Endorsements',
        href: '/cms/testimonials',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-landing-pages',
        title: 'Landing Page Builder',
        href: '/cms/landing-pages',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-seo',
        title: 'Global SEO Config',
        href: '/cms/seo',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-redirects',
        title: 'URL Redirect Rules',
        href: '/cms/redirects',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-sitemap',
        title: 'XML Sitemap Index',
        href: '/cms/sitemap',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-robots',
        title: 'Robots.txt Editor',
        href: '/cms/robots',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-schema',
        title: 'Schema Markup (JSON-LD)',
        href: '/cms/schema',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-meta-tags',
        title: 'Meta Tags Injection',
        href: '/cms/meta-tags',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-scheduler',
        title: 'Publishing Scheduler',
        href: '/cms/content-scheduler',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
      {
        id: 'cms-version-history',
        title: 'Revision Audit Logs',
        href: '/cms/version-history',
        icon: 'CircleDot',
        permission: 'view:cms',
      },
    ],
  },
  {
    id: 'reports',
    title: 'Reports & Business Intelligence',
    icon: 'BarChart3',
    permission: 'view:reports',
    children: [
      {
        id: 'reports-dashboard',
        title: 'Executive Dashboard',
        href: '/reports/dashboard',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-sales',
        title: 'Sales & Revenue',
        href: '/reports/sales',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-orders',
        title: 'Order Lifecycle',
        href: '/reports/orders',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-products',
        title: 'Product Performance',
        href: '/reports/products',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-categories',
        title: 'Category Share',
        href: '/reports/categories',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-customers',
        title: 'Customer & CLV',
        href: '/reports/customers',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-inventory',
        title: 'Inventory Valuation',
        href: '/reports/inventory',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-payments',
        title: 'Payment Gateways',
        href: '/reports/payments',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-refunds',
        title: 'Refunds & Returns',
        href: '/reports/refunds',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-tax',
        title: 'Tax & Compliance',
        href: '/reports/tax',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-marketing',
        title: 'Marketing ROI',
        href: '/reports/marketing',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-coupons',
        title: 'Coupons & Promos',
        href: '/reports/coupons',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-loyalty',
        title: 'Loyalty Program',
        href: '/reports/loyalty',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-shipping',
        title: 'Shipping & Carriers',
        href: '/reports/shipping',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-vendors',
        title: 'Vendors & Quality',
        href: '/reports/vendors',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-profit-loss',
        title: 'Profit & Loss (P&L)',
        href: '/reports/profit-loss',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-finance',
        title: 'Finance & Ledger',
        href: '/reports/finance',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-audit',
        title: 'Security Audit Logs',
        href: '/reports/audit',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-system',
        title: 'System Telemetry',
        href: '/reports/system',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-custom',
        title: 'Custom Query Builder',
        href: '/reports/custom',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-scheduled',
        title: 'Scheduled Delivery',
        href: '/reports/scheduled',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
      {
        id: 'reports-export-history',
        title: 'Export Archive Logs',
        href: '/reports/export-history',
        icon: 'CircleDot',
        permission: 'view:reports',
      },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications Hub',
    icon: 'Bell',
    children: [
      { id: 'notif-dashboard', title: 'Executive Overview', href: '/dashboard/notifications/dashboard', icon: 'CircleDot' },
      { id: 'notif-inbox', title: 'Inbox & Dispatches', href: '/dashboard/notifications/inbox', icon: 'CircleDot' },
      { id: 'notif-sent', title: 'Sent History', href: '/dashboard/notifications/sent', icon: 'CircleDot' },
      { id: 'notif-templates', title: 'Templates Engine', href: '/dashboard/notifications/templates', icon: 'CircleDot' },
      { id: 'notif-email', title: 'Email Center', href: '/dashboard/notifications/email', icon: 'CircleDot' },
      { id: 'notif-sms', title: 'SMS Gateway', href: '/dashboard/notifications/sms', icon: 'CircleDot' },
      { id: 'notif-whatsapp', title: 'WhatsApp Hub', href: '/dashboard/notifications/whatsapp', icon: 'CircleDot' },
      { id: 'notif-push', title: 'Push Notifications', href: '/dashboard/notifications/push', icon: 'CircleDot' },
      { id: 'notif-in-app', title: 'In-App Banners', href: '/dashboard/notifications/in-app', icon: 'CircleDot' },
      { id: 'notif-broadcast', title: 'Mass Broadcasts', href: '/dashboard/notifications/broadcast', icon: 'CircleDot' },
      { id: 'notif-campaigns', title: 'Campaigns', href: '/dashboard/notifications/campaigns', icon: 'CircleDot' },
      { id: 'notif-queue', title: 'Dispatch Queue', href: '/dashboard/notifications/queue', icon: 'CircleDot' },
      { id: 'notif-logs', title: 'Response Logs', href: '/dashboard/notifications/logs', icon: 'CircleDot' },
      { id: 'notif-preferences', title: 'Subscribers & GDPR', href: '/dashboard/notifications/preferences', icon: 'CircleDot' },
      { id: 'notif-webhooks', title: 'Webhooks', href: '/dashboard/notifications/webhooks', icon: 'CircleDot' },
      { id: 'notif-events', title: 'Event Triggers', href: '/dashboard/notifications/events', icon: 'CircleDot' },
      { id: 'notif-alerts', title: 'System Alerts', href: '/dashboard/notifications/alerts', icon: 'CircleDot' },
      { id: 'notif-monitoring', title: 'Gateway Health', href: '/dashboard/notifications/monitoring', icon: 'CircleDot' },
    ],
  },
  {
    id: 'system-admin',
    title: 'System Administration',
    icon: 'Cpu',
    permission: 'manage:system',
    children: [
      {
        id: 'system-dashboard',
        title: 'System Dashboard',
        href: '/dashboard/system/dashboard',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-company',
        title: 'Company Profile',
        href: '/dashboard/system/company',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-stores',
        title: 'Multi-Store Channels',
        href: '/dashboard/system/stores',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-theme',
        title: 'Theme & Customization',
        href: '/dashboard/system/theme',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-localization',
        title: 'Localization & Currencies',
        href: '/dashboard/system/localization',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-tax',
        title: 'Tax & Compliance',
        href: '/dashboard/system/tax',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-gateways',
        title: 'Communication Gateways',
        href: '/dashboard/system/gateways',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-api-keys',
        title: 'API Keys & Webhooks',
        href: '/dashboard/system/api-keys',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-feature-flags',
        title: 'Feature Toggles & Flags',
        href: '/dashboard/system/feature-flags',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-security',
        title: 'Security & Auth Policy',
        href: '/dashboard/system/security',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-roles',
        title: 'Roles & Permissions (RBAC)',
        href: '/dashboard/system/roles',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-users',
        title: 'User Provisioning',
        href: '/dashboard/system/users',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-logs',
        title: 'Security Audit Trail',
        href: '/dashboard/system/logs',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-health',
        title: 'Cluster Health Diagnostics',
        href: '/dashboard/system/health',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-cache',
        title: 'Cache & Memory Invalidation',
        href: '/dashboard/system/cache',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-backups',
        title: 'Disaster Recovery & Backups',
        href: '/dashboard/system/backups',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
      {
        id: 'system-license',
        title: 'Software Build & License',
        href: '/dashboard/system/license',
        icon: 'CircleDot',
        permission: 'manage:system',
      },
    ],
  },
];
