import {
  NotificationStats,
  NotificationItem,
  NotificationTemplate,
  NotificationCampaign,
  QueueItem,
  NotificationLog,
  SubscriberPreference,
  WebhookEndpoint,
  SystemEvent,
  SystemAlert,
  ProviderHealth,
  EmailMessage,
  SmsMessage,
  WhatsAppMessage,
  PushNotificationPayload,
  InAppNotificationConfig,
  BroadcastPayload,
} from '../types/notificationTypes';

export const mockStats: NotificationStats = {
  totalNotifications: 148290,
  pendingCount: 1420,
  queuedCount: 380,
  sentCount: 142100,
  deliveredCount: 139850,
  readCount: 104200,
  failedCount: 1140,
  emailDelivered: 84200,
  smsDelivered: 32100,
  whatsAppDelivered: 14800,
  pushDelivered: 8750,
  queueSize: 380,
  deliverySuccessRate: 98.4,
  openRate: 74.5,
  clickRate: 31.2,
};

export const mockNotifications: NotificationItem[] = [
  {
    id: 'NOTIF-8001',
    title: 'Order Dispatch Confirmation #ORD-99421',
    message: 'Your order has been shipped via Express Logistics. Tracking number: EX-8839201.',
    channel: 'email',
    status: 'delivered',
    priority: 'high',
    recipient: 'alex.smith@enterprise.com',
    recipientName: 'Alex Smith',
    sender: 'system@enterprise.io',
    templateId: 'TPL-EMAIL-ORDER-SHIP',
    sentAt: '2026-07-22 10:15:20',
    deliveredAt: '2026-07-22 10:15:24',
    readAt: '2026-07-22 10:18:00',
    retryCount: 0,
    isPinned: true,
    isStarred: true,
    folder: 'inbox',
  },
  {
    id: 'NOTIF-8002',
    title: 'Security Alert: New IP Login Detected',
    message: 'A login attempt was made from IP 192.168.1.105 in Zurich, Switzerland.',
    channel: 'email',
    status: 'delivered',
    priority: 'urgent',
    recipient: 'security@enterprise.com',
    recipientName: 'SecOps Team',
    sender: 'sec-bot@enterprise.io',
    templateId: 'TPL-EMAIL-SEC-ALERT',
    sentAt: '2026-07-22 09:30:10',
    deliveredAt: '2026-07-22 09:30:12',
    readAt: '2026-07-22 09:31:05',
    retryCount: 0,
    isPinned: true,
    folder: 'inbox',
  },
  {
    id: 'NOTIF-8003',
    title: '2FA Verification Code: 839210',
    message: 'Your single-use login passcode is 839210. Valid for 5 minutes.',
    channel: 'sms',
    status: 'delivered',
    priority: 'urgent',
    recipient: '+1 555-019-2834',
    recipientName: 'David Miller',
    sender: 'AUTH-SMS',
    sentAt: '2026-07-22 08:45:00',
    deliveredAt: '2026-07-22 08:45:02',
    retryCount: 0,
    folder: 'sent',
  },
  {
    id: 'NOTIF-8004',
    title: 'VIP Flash Sale Invitation',
    message: 'Exclusive 30% discount on Enterprise Cloud tiers for existing accounts.',
    channel: 'whatsapp',
    status: 'delivered',
    priority: 'normal',
    recipient: '+44 7700 900077',
    recipientName: 'Emma Watson',
    sender: 'Enterprise WhatsApp',
    sentAt: '2026-07-22 07:12:00',
    deliveredAt: '2026-07-22 07:12:05',
    readAt: '2026-07-22 07:25:40',
    retryCount: 0,
    folder: 'sent',
  },
  {
    id: 'NOTIF-8005',
    title: 'Payment Invoice Past Due #INV-8812',
    message: 'Invoice #INV-8812 for $12,450.00 is past due. Please review payment settings.',
    channel: 'email',
    status: 'failed',
    priority: 'high',
    recipient: 'billing@acme-corp.com',
    recipientName: 'Acme Billing',
    sender: 'billing@enterprise.io',
    sentAt: '2026-07-22 06:00:00',
    failedAt: '2026-07-22 06:00:15',
    failureReason: '550 5.1.1 Recipient address rejected: User unknown',
    retryCount: 3,
    folder: 'inbox',
  },
];

export const mockTemplates: NotificationTemplate[] = [
  {
    id: 'TPL-EMAIL-ORDER-SHIP',
    name: 'Order Dispatched Notification',
    code: 'EMAIL_ORDER_DISPATCH',
    channel: 'email',
    category: 'transactional',
    subject: 'Order {{order_id}} Dispatched',
    body: 'Hello {{user_name}},\n\nYour order #{{order_id}} has been shipped with carrier {{carrier}}.\nTracking Link: {{tracking_url}}\n\nThank you for choosing us!',
    variables: ['user_name', 'order_id', 'carrier', 'tracking_url'],
    version: 3,
    active: true,
    updatedAt: '2026-07-20',
  },
  {
    id: 'TPL-SMS-2FA',
    name: 'SMS Two-Factor Verification Code',
    code: 'SMS_AUTH_2FA',
    channel: 'sms',
    category: 'security',
    body: 'Your verification code is {{code}}. Valid for 5 minutes. Do not share code.',
    variables: ['code'],
    version: 1,
    active: true,
    updatedAt: '2026-06-12',
  },
  {
    id: 'TPL-WA-APPOINTMENT',
    name: 'WhatsApp Appointment Reminder',
    code: 'WA_APPT_REMIND',
    channel: 'whatsapp',
    category: 'transactional',
    body: 'Hi {{customer_name}}, this is a reminder for your upcoming session on {{date}} at {{time}}.',
    variables: ['customer_name', 'date', 'time'],
    version: 2,
    active: true,
    updatedAt: '2026-07-01',
  },
  {
    id: 'TPL-PUSH-BACK-IN-STOCK',
    name: 'Push Alert: Item Back In Stock',
    code: 'PUSH_STOCK_ALERT',
    channel: 'push',
    category: 'marketing',
    subject: '🔥 Back in Stock!',
    body: '{{product_name}} is now available again. Grab yours before it runs out!',
    variables: ['product_name'],
    version: 1,
    active: true,
    updatedAt: '2026-05-18',
  },
];

export const mockCampaigns: NotificationCampaign[] = [
  {
    id: 'CAMP-9001',
    name: 'Q3 Enterprise Product Upgrade Blast',
    description: 'Multi-channel announcement targeting active enterprise workspace admins.',
    channels: ['email', 'in-app'],
    targetAudience: 'Enterprise Workspace Admins (4,850 Users)',
    status: 'active',
    scheduledStart: '2026-07-21 09:00',
    totalSent: 4850,
    openRate: 82.4,
    clickRate: 44.1,
    conversionRate: 18.5,
  },
  {
    id: 'CAMP-9002',
    name: 'Re-engagement Discount Campaign',
    description: 'SMS and WhatsApp discount vouchers for inactive accounts (>90 days).',
    channels: ['sms', 'whatsapp'],
    targetAudience: 'Inactive Users (12,400 Users)',
    status: 'active',
    scheduledStart: '2026-07-22 12:00',
    totalSent: 9200,
    openRate: 68.2,
    clickRate: 22.8,
    conversionRate: 8.4,
  },
];

export const mockQueue: QueueItem[] = [
  {
    id: 'QUEUE-101',
    notificationId: 'NOTIF-9912',
    channel: 'email',
    recipient: 'ops-lead@global.com',
    queueType: 'pending',
    payloadSummary: 'Weekly System Security & Performance Digest',
    retryCount: 0,
    maxRetries: 3,
    enqueuedAt: '2026-07-22 13:40:00',
    nextAttemptAt: '2026-07-22 13:55:00',
  },
  {
    id: 'QUEUE-102',
    notificationId: 'NOTIF-9913',
    channel: 'sms',
    recipient: '+1 555-883-1290',
    queueType: 'retry',
    payloadSummary: 'Payment Failed Retry Alert #PAY-8821',
    retryCount: 2,
    maxRetries: 5,
    lastError: 'HTTP 429 Too Many Requests from SMS Carrier Gateway',
    enqueuedAt: '2026-07-22 13:20:00',
    nextAttemptAt: '2026-07-22 14:00:00',
  },
  {
    id: 'QUEUE-103',
    notificationId: 'NOTIF-9914',
    channel: 'whatsapp',
    recipient: '+49 151 23456789',
    queueType: 'dead_letter',
    payloadSummary: 'Account Renewal Voucher Offer',
    retryCount: 5,
    maxRetries: 5,
    lastError: 'Meta WhatsApp API: Invalid phone number format or non-WhatsApp user',
    enqueuedAt: '2026-07-22 11:00:00',
  },
];

export const mockLogs: NotificationLog[] = [
  {
    id: 'LOG-7701',
    notificationId: 'NOTIF-8001',
    channel: 'email',
    recipient: 'alex.smith@enterprise.com',
    status: 'delivered',
    provider: 'SendGrid v3 API',
    providerResponseCode: '202 Accepted',
    providerResponseBody: '{"message":"queued","msg_id":"SG.8831.Xz9"}',
    retryCount: 0,
    latencyMs: 142,
    timestamp: '2026-07-22 10:15:24',
  },
  {
    id: 'LOG-7702',
    notificationId: 'NOTIF-8003',
    channel: 'sms',
    recipient: '+1 555-019-2834',
    status: 'delivered',
    provider: 'Twilio Programmable Messaging',
    providerResponseCode: '200 OK',
    providerResponseBody: '{"sid":"SM8839201923","status":"delivered"}',
    retryCount: 0,
    latencyMs: 89,
    timestamp: '2026-07-22 08:45:02',
  },
  {
    id: 'LOG-7703',
    notificationId: 'NOTIF-8005',
    channel: 'email',
    recipient: 'billing@acme-corp.com',
    status: 'failed',
    provider: 'Amazon SES',
    providerResponseCode: '550 User Unknown',
    providerResponseBody: '{"Code":"MessageRejected","Message":"Email address not found"}',
    retryCount: 3,
    latencyMs: 650,
    timestamp: '2026-07-22 06:00:15',
  },
];

export const mockSubscribers: SubscriberPreference[] = [
  {
    id: 'SUB-3001',
    userId: 'USR-1002',
    userName: 'Alexander Wright',
    email: 'alexander.w@cloudcorp.com',
    phone: '+1 555-908-1122',
    channels: { email: true, sms: true, whatsapp: true, push: false, inApp: true },
    categories: { orders: true, marketing: false, security: true, systemAlerts: true },
    status: 'opt_in',
    updatedAt: '2026-07-15',
  },
  {
    id: 'SUB-3002',
    userId: 'USR-1003',
    userName: 'Sophia Martinez',
    email: 'sophia.m@fintech.io',
    phone: '+1 555-321-7788',
    channels: { email: true, sms: false, whatsapp: false, push: true, inApp: true },
    categories: { orders: true, marketing: true, security: true, systemAlerts: false },
    status: 'opt_in',
    updatedAt: '2026-07-18',
  },
];

export const mockWebhooks: WebhookEndpoint[] = [
  {
    id: 'WH-501',
    name: 'Datadog Alert Ingestion Webhook',
    url: 'https://api.datadoghq.com/v1/input/notif-events-key-8812',
    secret: 'whsec_99182371239812739812',
    events: ['notification.failed', 'notification.bounced', 'queue.dead_letter'],
    status: 'active',
    successRate: 99.8,
    lastTriggeredAt: '2026-07-22 13:10:00',
    failureCount: 1,
  },
  {
    id: 'WH-502',
    name: 'Slack SecOps Escalation Channel',
    url: 'https://hooks.slack.com/services/T00/B00/XXXXX',
    secret: 'whsec_slack_secops_secret_token',
    events: ['alert.critical', 'security.login_failed'],
    status: 'active',
    successRate: 100.0,
    lastTriggeredAt: '2026-07-22 09:30:12',
    failureCount: 0,
  },
];

export const mockSystemEvents: SystemEvent[] = [
  {
    id: 'EVT-100',
    eventType: 'order.created',
    category: 'order',
    description: 'Triggered immediately when a new customer order is placed and authorized.',
    triggerChannel: ['email', 'sms', 'in-app'],
    templateId: 'TPL-EMAIL-ORDER-SHIP',
    enabled: true,
    lastTriggered: '2026-07-22 13:42:10',
    triggeredCount: 18420,
  },
  {
    id: 'EVT-101',
    eventType: 'payment.success',
    category: 'payment',
    description: 'Triggered when payment gateway confirms successful fund charge or authorization.',
    triggerChannel: ['email', 'whatsapp'],
    templateId: 'TPL-WA-APPOINTMENT',
    enabled: true,
    lastTriggered: '2026-07-22 13:40:05',
    triggeredCount: 17950,
  },
  {
    id: 'EVT-102',
    eventType: 'inventory.low',
    category: 'inventory',
    description: 'Triggered when product inventory falls below safety reorder threshold.',
    triggerChannel: ['email', 'in-app', 'push'],
    templateId: 'TPL-PUSH-BACK-IN-STOCK',
    enabled: true,
    lastTriggered: '2026-07-22 11:15:00',
    triggeredCount: 420,
  },
];

export const mockAlerts: SystemAlert[] = [
  {
    id: 'ALT-901',
    severity: 'critical',
    title: 'Twilio SMS Gateway Throughput Throttled',
    source: 'SMS Dispatch Worker #04',
    message: 'Twilio HTTP 429 response rate exceeded 8% over 10 minutes. SMS delivery latency elevated.',
    status: 'active',
    createdAt: '2026-07-22 13:15:00',
  },
  {
    id: 'ALT-902',
    severity: 'warning',
    title: 'Dead Letter Queue Exceeded 50 Items',
    source: 'Notification Queue Worker',
    message: 'Dead letter queue size reached 52 failed items. Manual inspection or retry recommended.',
    status: 'active',
    createdAt: '2026-07-22 12:40:00',
  },
  {
    id: 'ALT-903',
    severity: 'info',
    title: 'Scheduled Maintenance Complete: SES Mail Relay',
    source: 'Infrastructure Monitor',
    message: 'Amazon SES mail relay IP pool rotation completed without packet loss.',
    status: 'resolved',
    createdAt: '2026-07-22 04:00:00',
    resolvedAt: '2026-07-22 04:30:00',
  },
];

export const mockProviderHealth: ProviderHealth[] = [
  {
    providerName: 'SendGrid Email API',
    channel: 'email',
    status: 'operational',
    uptime99: 99.98,
    avgLatencyMs: 120,
    errorRate: 0.02,
    activeRateLimit: '10,000 req/min',
    lastPing: '2026-07-22 13:54:00',
  },
  {
    providerName: 'Twilio SMS Gateway',
    channel: 'sms',
    status: 'degraded',
    uptime99: 98.40,
    avgLatencyMs: 850,
    errorRate: 2.15,
    activeRateLimit: '2,500 req/min',
    lastPing: '2026-07-22 13:54:10',
  },
  {
    providerName: 'Meta WhatsApp Business API',
    channel: 'whatsapp',
    status: 'operational',
    uptime99: 99.95,
    avgLatencyMs: 180,
    errorRate: 0.05,
    activeRateLimit: '5,000 req/min',
    lastPing: '2026-07-22 13:53:50',
  },
  {
    providerName: 'Firebase Cloud Messaging (FCM)',
    channel: 'push',
    status: 'operational',
    uptime99: 99.99,
    avgLatencyMs: 65,
    errorRate: 0.01,
    activeRateLimit: '50,000 req/min',
    lastPing: '2026-07-22 13:54:12',
  },
];
